### ISSUE TITLE
WIndows

### ISSUE THREAD

**Issue by kyle-goodwin** [fullyautomated/KiJLC#5]
Is this supposed to work in Windows?

I've cloned it to both the following directories and neither work.

%KICAD_INSTALL_PATH%/share/kicad/scripting/plugins
%APPDATA%/Roaming/kicad/scripting/plugins

**Comment by kyle-goodwin** [comment]
So this doesn't work on WIndows?

`Py 0.9.8
Python 2.7.18 (default, Apr 20 2020, 16:57:11)  [GCC 9.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Startup script executed: C:\Users\Karl\AppData\Roaming\kicad\PyShell_pcbnew_startup.py

import pcbnew

print(pcbnew.NOT_LOADED_WIZARDS)
Skip subdir C:\Users\Karl\AppData\Roaming\kicad\scripting\plugins
C:\Users\Karl\AppData\Roaming\kicad\scripting\plugins\KiJLC

print(pcbnew.FULL_BACK_TRACE)
Traceback (most recent call last):
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 2947, in LoadPluginModule
    mod = reload( plugin["ModuleName"] )
  File "C:\Users\Karl\AppData\Roaming\kicad\scripting\plugins/KiJLC/__init__.py", line 185
    print(f"previous midpoint for {footprint} x: {mid_x}, y: {mid_y}; new x: {mid_x + qx}, y: {mid_y + qy}")
                                                                                                          ^
SyntaxError: invalid syntax`

**Comment by tachiniererin** [comment]
sorry, i never tested this on windows because i don't have it installed on any of my machines. the error is because the python install (either bundled or otherwise on that system) is Python 2.7. i'm not sure if kicad comes with it by default, but that version has been deprecated last year already i think. the plugin only works with Python 3. i'll see if i can set up a windows machine when i update the plugin for kicad 6 and test it with that.

**Comment by kyle-goodwin** [comment]
That makes sense. I made the bad assumption that a newer version of Kicad (on Windows) would use at least an up to date version of Python. My linux machine is running Kicad 5.1.5 which bundles Python 3.8 and my Windows machine is running Kicad 5.1.9 which bundles Python 2.7.

I did not realize Kicad 6.0 was out now. I'll download it and test this.

**Comment by kyle-goodwin** [comment]
KiCad 6.0 on WIndows comes with Python 3.9.6. Plugin loads fine but does not actually work due to the issues pointed out in the active pull requests.  The fork from @egilkv works great.
